---
title: "Light/Dark Pathways Workflow"
author: "Ted Laderas"
date: "6/6/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Reproducing HNSCC notebook

This notebook and repo contains everything needed to reproduce the light/dark pathway analysis in Choonoo, et al.

```{r}
library(here)
library("packageDir")
library("roxygen2")
library("rBiopaxParser")
library("stringr")
```

## Processing Pathway Information



```{r include=FALSE}
path_detail <- getDefaultPaths("reference_data/paths/ReactomePathways 2015 02 17 13 46 25 2019.06.10 18.48.35.txt")
saveRDS(path_detail, file="data/path_detail.rds")
```

## Running Overlap analysis

A number of settings options have to be set for this analysis. 

```{r}
path_detail <- readRDS("data/path_detail.rds")

settings <- getBasicSettings()

#modify the settings object
settings$somatic_mutation_aberration_summary$interactive <- "n"

settings$somatic_mutation_aberration_summary$`Analyze pathways for individual members of the cohort? (y or n) `<- "n"

settings$somatic_mutation_aberration_summary$`Select a .maf file containing the data set to be analyzed.` <- "data/TCGA.HNSC.mutect.84c7a87a-9dcc-48fb-bd69-ba9d6e6f3ca2.DR-7.0.somatic_cleaned.maf"

settings$somatic_mutation_aberration_summary$`Would you like to include PolyPhen analysis results in this analysis? (y/n) `<- "n"

settings$somatic_mutation_aberration_summary$`Have manual gene symbol corrections already been conducted? (y/n)` <- "y"

settings$somatic_mutation_aberration_summary$`Analyze pathways for individual members of the cohort? (y or n) ` <- "n"

settings$somatic_mutation_aberration_summary$`Have manual gene symbol corrections already been conducted? (y/n)` <- "y"

settings$somatic_mutation_aberration_summary$`
Please enter the row numbers of the variant types you would like to analyze (sepparated by a space).
` <- "Frame_Shift_Del; Frame_Shift_Ins; In_Frame_Del; In_Frame_Ins; Missense_Mutation; Nonsense_Mutation; Nonstop_Mutation; Splice_Site"

settings$somatic_mutation_aberration_summary$`Would you like to filter out hypermutators?
If yes, please enter a mutation count threshold.
If no just press enter n ` <- "n"

settings$somatic_mutation_aberration_summary$`Use special path significance analysis settings for this data type? (y/n)` <- "n"
 
```


# Process Drug Screen Settings

```{r}
settings$functional_drug_screen_summary$`Please select a file with a drug screen results data set
` <- "data/Targetome_Level123_8_7_17.txt"

settings$functional_drug_screen_summary$interactive <- "n"

settings$functional_drug_screen_summary$`Have manual symbol corrections been performed yet for the current data set? (y/n)` <- "y"

settings$functional_drug_screen_summary$`Analyze pathways for individual members of the cohort? (y or n) ` <- "n"

settings$functional_drug_screen_summary$`
 To analyze drug screen panel coverage (for a panel that has or has not been run), enter p
 To process drug screen result set enter d
 To save an HTML summary of the results enter h
 To exit drug screen interface, enter q
` <- "p"
 
 settings$functional_drug_screen_summary$`Please select a file with a drug screen results data set
` <- "data/Targetome_Level123_8_7_17.txt"
 
 settings$functional_drug_screen_summary$`Have manual symbol corrections been performed yet for the current data set? (y/n)` <- "y"


#select gene, not target


study = getStudyObject(study.name="hnscc", 
											 geneIdentifierType="HUGO",
											 path_detail = path_detail, 
											 settings = settings)
```

## Running the Analysis



```{r}
study <- loadBasicArms(study)
study <- autoRunFromSettings(study)
saveStudy(study)

```


